# src/atlas/embeddings/semantic_fusion.py

# ============================================================
# SEMANTIC FUSION
#
# Purpose:
#   Combine an existing TF-IDF semantic representation with
#   Sentence-BERT review embeddings.
#
#
# Method:
#
#   TF-IDF
#      ↓
#   TruncatedSVD
#      ↓
#   L2 normalization
#      │
#      ├───────────── weighted concatenation
#      │
#   SBERT reviews
#      ↓
#   align by entity ID
#      ↓
#   L2 normalization
#
#
# Weighting:
#
#   review_share = r
#
#   TF-IDF block weight = sqrt(1 - r)
#   Review block weight = sqrt(r)
#
# This means that, for entities with both representations,
# cosine similarity in the fused space is approximately:
#
#   (1 - r) * TF-IDF similarity
#       +
#   r * review similarity
#
#
# Entities without review embeddings are NOT removed.
# They simply retain their TF-IDF representation.
#
# ============================================================


from pathlib import Path

import numpy as np

from sklearn.decomposition import TruncatedSVD
from sklearn.preprocessing import normalize


# ============================================================
# ID NORMALIZATION
# ============================================================


def _entity_id_key(value):
    """
    Convert entity IDs into stable comparable strings.

    This allows the same fusion module to work with:

        movieId       -> integer
        mbid          -> string
        business_id   -> string
    """

    if isinstance(
        value,
        bytes
    ):

        value = value.decode(
            "utf-8"
        )

    # --------------------------------------------------------
    # Integer-like IDs
    # --------------------------------------------------------

    if isinstance(
        value,
        (
            int,
            np.integer
        )
    ):

        return str(
            int(value)
        )

    # --------------------------------------------------------
    # Float IDs that are actually integers
    #
    # Example:
    #     1.0 -> "1"
    # --------------------------------------------------------

    if isinstance(
        value,
        (
            float,
            np.floating
        )
    ):

        if np.isfinite(value):

            if float(value).is_integer():

                return str(
                    int(value)
                )

    return str(
        value
    ).strip()


# ============================================================
# LOAD REVIEW EMBEDDINGS
# ============================================================


def load_review_embeddings(
    review_embeddings_path
):
    """
    Load an embedding .npz generated by the reusable
    review embedding pipeline.

    Expected arrays:

        entity_ids
        embeddings
        review_counts
    """

    review_embeddings_path = Path(
        review_embeddings_path
    )

    if not review_embeddings_path.exists():

        raise FileNotFoundError(
            "Review embedding file not found:\n"
            f"{review_embeddings_path}"
        )

    data = np.load(
        review_embeddings_path,
        allow_pickle=False
    )

    required_keys = {

        "entity_ids",
        "embeddings",
        "review_counts"

    }

    missing_keys = (
        required_keys
        - set(data.files)
    )

    if missing_keys:

        raise ValueError(
            "Review embedding file is missing "
            f"required arrays: {missing_keys}"
        )

    entity_ids = data[
        "entity_ids"
    ]

    embeddings = data[
        "embeddings"
    ].astype(
        np.float32,
        copy=False
    )

    review_counts = data[
        "review_counts"
    ]

    # --------------------------------------------------------
    # Shape validation
    # --------------------------------------------------------

    if embeddings.ndim != 2:

        raise ValueError(
            "Review embeddings must be a "
            "2D matrix."
        )

    if len(entity_ids) != len(
        embeddings
    ):

        raise ValueError(
            "entity_ids and embeddings have "
            "different lengths."
        )

    if len(review_counts) != len(
        embeddings
    ):

        raise ValueError(
            "review_counts and embeddings have "
            "different lengths."
        )

    return (
        entity_ids,
        embeddings,
        review_counts
    )


# ============================================================
# TF-IDF REDUCTION
# ============================================================


def reduce_tfidf_embeddings(
    tfidf_matrix,
    n_components=256,
    random_state=42
):
    """
    Reduce the sparse TF-IDF matrix using TruncatedSVD.

    TruncatedSVD is appropriate for sparse TF-IDF data
    and avoids converting the original high-dimensional
    sparse matrix to dense form first.

    The resulting vectors are L2-normalized.
    """

    if tfidf_matrix is None:

        raise ValueError(
            "tfidf_matrix cannot be None."
        )

    if len(
        tfidf_matrix.shape
    ) != 2:

        raise ValueError(
            "tfidf_matrix must be 2-dimensional."
        )

    n_samples = (
        tfidf_matrix.shape[0]
    )

    n_features = (
        tfidf_matrix.shape[1]
    )

    # --------------------------------------------------------
    # Ensure requested dimensionality is valid.
    # --------------------------------------------------------

    max_components = min(

        n_components,

        n_samples - 1,

        n_features - 1

    )

    if max_components <= 0:

        raise ValueError(
            "TF-IDF matrix is too small for "
            "TruncatedSVD."
        )

    if max_components != n_components:

        print(
            f"Requested {n_components} SVD components, "
            f"using {max_components} instead."
        )

    print(
        f"Reducing TF-IDF: "
        f"{n_features:,}D -> "
        f"{max_components:,}D"
    )

    svd_model = TruncatedSVD(

        n_components=max_components,

        random_state=random_state

    )

    reduced = svd_model.fit_transform(
        tfidf_matrix
    )

    reduced = reduced.astype(
        np.float32,
        copy=False
    )

    # --------------------------------------------------------
    # L2 normalize each entity.
    # --------------------------------------------------------

    reduced = normalize(

        reduced,

        norm="l2",

        axis=1,

        copy=False

    )

    reduced = reduced.astype(
        np.float32,
        copy=False
    )

    explained_variance = float(
        svd_model
        .explained_variance_ratio_
        .sum()
    )

    print(
        f"SVD explained variance: "
        f"{explained_variance:.4f}"
    )

    return (
        reduced,
        svd_model
    )


# ============================================================
# ALIGN REVIEW EMBEDDINGS
# ============================================================


def align_review_embeddings(
    entity_ids,
    review_embedding_ids,
    review_embeddings,
    review_counts
):
    """
    Align review embeddings to the entity ordering used
    by the current atlas dataframe.

    Example:

        entity_ids:
            [1, 2, 3, 4]

        review embedding IDs:
            [1, 3]

    becomes:

        entity 1 -> review embedding
        entity 2 -> zero vector
        entity 3 -> review embedding
        entity 4 -> zero vector

    Entities without reviews therefore remain available
    in the atlas.
    """

    embedding_dimension = (
        review_embeddings.shape[1]
    )

    aligned_embeddings = np.zeros(

        (
            len(entity_ids),
            embedding_dimension
        ),

        dtype=np.float32

    )

    aligned_counts = np.zeros(

        len(entity_ids),

        dtype=np.int32

    )

    # --------------------------------------------------------
    # Build lookup.
    # --------------------------------------------------------

    review_lookup = {}

    for index, entity_id in enumerate(
        review_embedding_ids
    ):

        key = _entity_id_key(
            entity_id
        )

        if key in review_lookup:

            raise ValueError(
                "Duplicate entity ID found in "
                "review embedding file: "
                f"{entity_id}"
            )

        review_lookup[
            key
        ] = index

    # --------------------------------------------------------
    # Align.
    # --------------------------------------------------------

    matched = 0

    for target_index, entity_id in enumerate(
        entity_ids
    ):

        key = _entity_id_key(
            entity_id
        )

        source_index = review_lookup.get(
            key
        )

        if source_index is None:

            continue

        aligned_embeddings[
            target_index
        ] = review_embeddings[
            source_index
        ]

        aligned_counts[
            target_index
        ] = int(
            review_counts[
                source_index
            ]
        )

        matched += 1

    # --------------------------------------------------------
    # Normalize again defensively.
    #
    # The SBERT pipeline already outputs normalized vectors,
    # but doing this here guarantees that the fusion assumptions
    # remain correct if the embedding pipeline changes later.
    # --------------------------------------------------------

    aligned_embeddings = normalize(

        aligned_embeddings,

        norm="l2",

        axis=1,

        copy=False

    )

    aligned_embeddings = (
        aligned_embeddings.astype(
            np.float32,
            copy=False
        )
    )

    print(
        f"Review embeddings aligned: "
        f"{matched:,} / "
        f"{len(entity_ids):,} entities"
    )

    return (
        aligned_embeddings,
        aligned_counts
    )


# ============================================================
# PREPARE FUSION COMPONENTS
# ============================================================


def prepare_semantic_fusion_components(
    tfidf_matrix,
    entity_ids,
    review_embeddings_path,
    tfidf_components=256,
    random_state=42
):
    """
    Prepare the two normalized semantic components used
    for fusion.

    Returns:

        tfidf_reduced
        review_aligned
        review_counts
        information
    """

    # ========================================================
    # TF-IDF
    # ========================================================

    (
        tfidf_reduced,
        svd_model

    ) = reduce_tfidf_embeddings(

        tfidf_matrix=tfidf_matrix,

        n_components=tfidf_components,

        random_state=random_state

    )

    # ========================================================
    # REVIEWS
    # ========================================================

    (
        review_embedding_ids,
        review_embeddings,
        review_counts

    ) = load_review_embeddings(

        review_embeddings_path

    )

    (
        review_aligned,
        aligned_review_counts

    ) = align_review_embeddings(

        entity_ids=entity_ids,

        review_embedding_ids=
            review_embedding_ids,

        review_embeddings=
            review_embeddings,

        review_counts=
            review_counts

    )

    information = {

        "tfidf_components":
            int(
                tfidf_reduced.shape[1]
            ),

        "review_components":
            int(
                review_aligned.shape[1]
            ),

        "entities":
            int(
                len(entity_ids)
            ),

        "entities_with_reviews":
            int(
                (
                    aligned_review_counts > 0
                ).sum()
            ),

        "svd_explained_variance":
            float(
                svd_model
                .explained_variance_ratio_
                .sum()
            )

    }

    return (
        tfidf_reduced,
        review_aligned,
        aligned_review_counts,
        information
    )


# ============================================================
# COMBINE SEMANTIC COMPONENTS
# ============================================================


def combine_semantic_components(
    tfidf_embeddings,
    review_embeddings,
    review_share=0.5
):
    """
    Fuse normalized TF-IDF and review representations.

    review_share:
        0.0 -> TF-IDF only
        0.5 -> balanced contribution
        1.0 -> reviews only

    For normal atlas generation we expect a value between
    these extremes.

    Entities without reviews retain their TF-IDF direction.
    """

    if not 0.0 <= review_share <= 1.0:

        raise ValueError(
            "review_share must be between "
            "0.0 and 1.0."
        )

    if tfidf_embeddings.shape[0] != (
        review_embeddings.shape[0]
    ):

        raise ValueError(
            "TF-IDF and review matrices must "
            "contain the same number of entities."
        )

    # --------------------------------------------------------
    # Square-root block weighting.
    #
    # Because each block has unit L2 norm, this causes
    # cosine similarity to behave approximately as:
    #
    #   (1-r) * similarity_tfidf
    #   +
    #   r * similarity_reviews
    # --------------------------------------------------------

    tfidf_weight = np.sqrt(
        1.0 - review_share
    )

    review_weight = np.sqrt(
        review_share
    )

    weighted_tfidf = (

        tfidf_embeddings

        *

        tfidf_weight

    )

    weighted_reviews = (

        review_embeddings

        *

        review_weight

    )

    fused = np.concatenate(

        [
            weighted_tfidf,
            weighted_reviews
        ],

        axis=1

    ).astype(
        np.float32,
        copy=False
    )

    # --------------------------------------------------------
    # Final normalization.
    #
    # Reviewed entities already have approximately unit norm.
    #
    # For entities without reviews, this rescales their
    # TF-IDF-only representation back to unit norm.
    # --------------------------------------------------------

    fused = normalize(

        fused,

        norm="l2",

        axis=1,

        copy=False

    )

    fused = fused.astype(
        np.float32,
        copy=False
    )

    return fused


# ============================================================
# COMPLETE FUSION PIPELINE
# ============================================================


def fuse_semantic_embeddings(
    tfidf_matrix,
    entity_ids,
    review_embeddings_path,
    review_share=0.5,
    tfidf_components=256,
    random_state=42,
    return_info=False
):
    """
    Convenience wrapper used by atlas pipelines.

    Example:

        semantic_matrix = fuse_semantic_embeddings(
            tfidf_matrix=tfidf_matrix,
            entity_ids=df["movieId"].to_numpy(),
            review_embeddings_path=...,
            review_share=0.5
        )
    """

    print()
    print("=" * 60)
    print("FUSING SEMANTIC REPRESENTATIONS")
    print("=" * 60)

    print(
        f"Review share:      "
        f"{review_share:.2f}"
    )

    print(
        f"TF-IDF share:      "
        f"{1.0 - review_share:.2f}"
    )

    print(
        f"TF-IDF components: "
        f"{tfidf_components}"
    )

    (
        tfidf_reduced,
        review_aligned,
        review_counts,
        information

    ) = prepare_semantic_fusion_components(

        tfidf_matrix=
            tfidf_matrix,

        entity_ids=
            entity_ids,

        review_embeddings_path=
            review_embeddings_path,

        tfidf_components=
            tfidf_components,

        random_state=
            random_state

    )

    fused = combine_semantic_components(

        tfidf_embeddings=
            tfidf_reduced,

        review_embeddings=
            review_aligned,

        review_share=
            review_share

    )

    information[
        "review_share"
    ] = float(
        review_share
    )

    information[
        "tfidf_share"
    ] = float(
        1.0 - review_share
    )

    information[
        "fused_dimensions"
    ] = int(
        fused.shape[1]
    )

    print(
        f"Fused matrix shape: "
        f"{fused.shape}"
    )

    print(
        f"Entities with reviews: "
        f"{information['entities_with_reviews']:,}"
    )

    if return_info:

        return (
            fused,
            information,
            review_counts
        )

    return fused