# src/domains/music/prepare_music_reviews.py

# ============================================================
# PREPARE CRITIQUEBRAINZ MUSIC REVIEWS
#
# Purpose:
#
#   1. Load CritiqueBrainz reviews already matched to artists
#      through MusicBrainz MBIDs
#
#   2. Remove duplicate review IDs
#
#   3. Clean and standardize review-level fields
#
#   4. Preserve individual review text for Sentence-BERT
#
#   5. Create a compact artist-level review summary
#
#
# Input:
#
#   data/data_scraping/
#       critiquebrainz_matched_reviews.csv
#
#
# Outputs:
#
#   data/processed/reviews/
#       music_reviews_prepared.csv
#
#       music_review_summary.csv
#
#
# Important:
#
#   This script DOES NOT:
#
#       - perform artist matching
#       - use fuzzy matching
#       - generate Sentence-BERT embeddings
#       - concatenate reviews into one giant artist string
#       - remove artists with only one review
#
#
# MusicBrainz artist MBID is treated as the canonical
# artist identifier.
#
# ============================================================


from pathlib import Path
import re

import numpy as np
import pandas as pd


# ============================================================
# PATHS
# ============================================================

ROOT = Path(__file__).resolve().parents[3]


# ------------------------------------------------------------
# Input generated by:
#
#   data/data_scraping/Critique_Brainz_Scraping.py
# ------------------------------------------------------------

INPUT_FILE = (
    ROOT
    / "data"
    / "data_scraping"
    / "critiquebrainz_matched_reviews.csv"
)


# ------------------------------------------------------------
# Outputs
# ------------------------------------------------------------

OUTPUT_DIR = (
    ROOT
    / "data"
    / "processed"
    / "reviews"
)

OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


OUTPUT_REVIEWS = (
    OUTPUT_DIR
    / "music_reviews_prepared.csv"
)


OUTPUT_SUMMARY = (
    OUTPUT_DIR
    / "music_review_summary.csv"
)


# ============================================================
# EXPECTED INPUT COLUMNS
# ============================================================

REQUIRED_COLUMNS = [

    "review_id",

    "original_entity_id",

    "original_entity_type",

    "artist_mbid",

    "artist_name_musicbrainz",

    "artist_name_dataset",

    "matched",

    "language",

    "created",

    "rating",

    "text",

    "info_url",

]


# ============================================================
# FINAL REVIEW-LEVEL OUTPUT COLUMNS
# ============================================================

OUTPUT_COLUMNS = [

    "artist_mbid",

    "review_id",

    "review_text",

    "rating",

    "review_date",

    "language",

    "original_entity_type",

    "original_entity_id",

    "artist_name_musicbrainz",

    "artist_name_dataset",

    "review_char_count",

    "review_word_count",

    "source",

]


# ============================================================
# VALIDATE INPUT
# ============================================================


def validate_input_file():

    if not INPUT_FILE.exists():

        raise FileNotFoundError(

            "CritiqueBrainz matched review file "
            "was not found:\n"
            f"{INPUT_FILE}"

        )


    columns = (

        pd.read_csv(
            INPUT_FILE,
            nrows=0
        )
        .columns
        .tolist()

    )


    missing_columns = [

        column

        for column
        in REQUIRED_COLUMNS

        if column not in columns

    ]


    if missing_columns:

        raise ValueError(

            "CritiqueBrainz review file is missing "
            "required columns:\n"
            f"{missing_columns}"

        )


# ============================================================
# BOOLEAN NORMALIZATION
# ============================================================


def normalize_boolean(
    series
):
    """
    Convert common CSV boolean values to True / False.

    Examples:

        True
        False
        "true"
        "false"
        1
        0
    """

    return (

        series
        .astype("string")
        .str.strip()
        .str.lower()
        .map({

            "true": True,

            "false": False,

            "1": True,

            "0": False,

            "yes": True,

            "no": False,

        })

    )


# ============================================================
# CLEAN REVIEW TEXT
# ============================================================


def clean_review_text(
    text
):
    """
    Clean review text conservatively for Sentence-BERT.

    We deliberately DO NOT:

        - lowercase
        - remove stop words
        - stem
        - lemmatize
        - strip punctuation

    Sentence-BERT should receive natural language.

    We only normalize whitespace.
    """

    if pd.isna(text):

        return ""


    text = str(
        text
    )


    # --------------------------------------------------------
    # Normalize line breaks / tabs / repeated whitespace
    # into simple spaces.
    # --------------------------------------------------------

    text = re.sub(

        r"\s+",

        " ",

        text

    )


    return text.strip()


# ============================================================
# CLEAN REVIEW DATASET
# ============================================================


def prepare_review_dataset():
    """
    Prepare one clean row per unique CritiqueBrainz review.
    """

    print()
    print("=" * 60)
    print("PREPARING CRITIQUEBRAINZ MUSIC REVIEWS")
    print("=" * 60)
    print()


    validate_input_file()


    print(
        "Input:"
    )

    print(
        INPUT_FILE
    )

    print()


    reviews = pd.read_csv(

        INPUT_FILE,

        low_memory=False

    )


    input_rows = len(
        reviews
    )


    # ========================================================
    # MATCH STATUS
    # ========================================================

    matched = normalize_boolean(
        reviews["matched"]
    )


    unmatched_mask = (
        matched != True
    )


    unmatched_removed = int(
        unmatched_mask.sum()
    )


    reviews = reviews[

        matched == True

    ].copy()


    # ========================================================
    # ARTIST MBID
    # ========================================================

    reviews["artist_mbid"] = (

        reviews["artist_mbid"]
        .astype("string")
        .str.strip()

    )


    invalid_artist_mask = (

        reviews["artist_mbid"].isna()

        |

        (
            reviews["artist_mbid"]
            == ""
        )

    )


    invalid_artist_rows = int(
        invalid_artist_mask.sum()
    )


    reviews = reviews[

        ~invalid_artist_mask

    ].copy()


    # ========================================================
    # REVIEW ID
    # ========================================================

    reviews["review_id"] = (

        reviews["review_id"]
        .astype("string")
        .str.strip()

    )


    missing_review_id_mask = (

        reviews["review_id"].isna()

        |

        (
            reviews["review_id"]
            == ""
        )

    )


    missing_review_ids = int(
        missing_review_id_mask.sum()
    )


    reviews = reviews[

        ~missing_review_id_mask

    ].copy()


    # --------------------------------------------------------
    # Check duplicate IDs for conflicting artists BEFORE
    # deduplication.
    #
    # Our diagnostic found zero conflicts, but preserving
    # this validation makes the preparation script safer.
    # --------------------------------------------------------

    duplicate_rows = reviews[

        reviews["review_id"]
        .duplicated(
            keep=False
        )

    ].copy()


    if len(
        duplicate_rows
    ) > 0:

        duplicate_artist_counts = (

            duplicate_rows
            .groupby(
                "review_id"
            )["artist_mbid"]
            .nunique()

        )


        conflicting_ids = (

            duplicate_artist_counts[
                duplicate_artist_counts > 1
            ]
            .index
            .tolist()

        )


        if conflicting_ids:

            raise ValueError(

                "Some duplicate CritiqueBrainz review IDs "
                "are linked to multiple artists.\n\n"
                f"Conflicting IDs: "
                f"{conflicting_ids[:10]}\n\n"
                "Review preparation stopped rather than "
                "choosing an artist arbitrarily."

            )


    # --------------------------------------------------------
    # Duplicate IDs are harmless exact/repeated review rows
    # when they still map to the same artist.
    #
    # Keep the first deterministic occurrence.
    # --------------------------------------------------------

    before_deduplication = len(
        reviews
    )


    reviews = reviews.drop_duplicates(

        subset=[
            "review_id"
        ],

        keep="first"

    ).copy()


    duplicates_removed = (

        before_deduplication

        -

        len(
            reviews
        )

    )


    # ========================================================
    # REVIEW TEXT
    # ========================================================

    reviews["review_text"] = (

        reviews["text"]
        .apply(
            clean_review_text
        )

    )


    empty_text_mask = (

        reviews[
            "review_text"
        ]
        == ""

    )


    empty_text_removed = int(
        empty_text_mask.sum()
    )


    reviews = reviews[

        ~empty_text_mask

    ].copy()


    # ========================================================
    # REVIEW RATING
    # ========================================================

    reviews["rating"] = pd.to_numeric(

        reviews["rating"],

        errors="coerce"

    )


    # CritiqueBrainz ratings in this dataset were observed
    # on a 1–5 scale.
    #
    # Invalid values become missing rather than causing the
    # review text to be removed.
    invalid_rating_mask = (

        reviews["rating"].notna()

        &

        (
            (reviews["rating"] < 1)

            |

            (reviews["rating"] > 5)
        )

    )


    invalid_ratings = int(
        invalid_rating_mask.sum()
    )


    reviews.loc[

        invalid_rating_mask,

        "rating"

    ] = np.nan


    # ========================================================
    # DATE
    # ========================================================

    reviews["review_date"] = (

        reviews["created"]
        .astype("string")
        .str.strip()

    )


    reviews.loc[

        reviews["review_date"]
        .isin(
            [
                "",
                "<NA>",
                "nan",
                "None"
            ]
        ),

        "review_date"

    ] = pd.NA


    # ========================================================
    # LANGUAGE
    # ========================================================

    reviews["language"] = (

        reviews["language"]
        .astype("string")
        .str.strip()
        .str.lower()

    )


    # ========================================================
    # ENTITY TYPE
    # ========================================================

    reviews[
        "original_entity_type"
    ] = (

        reviews[
            "original_entity_type"
        ]
        .astype("string")
        .str.strip()
        .str.lower()

    )


    # --------------------------------------------------------
    # We deliberately keep both:
    #
    #     artist
    #     release_group
    #
    # because reviews of an artist's releases provide useful
    # semantic information about that artist's music.
    # --------------------------------------------------------


    # ========================================================
    # ORIGINAL ENTITY ID
    # ========================================================

    reviews[
        "original_entity_id"
    ] = (

        reviews[
            "original_entity_id"
        ]
        .astype("string")
        .str.strip()

    )


    # ========================================================
    # ARTIST NAMES
    # ========================================================

    reviews[
        "artist_name_musicbrainz"
    ] = (

        reviews[
            "artist_name_musicbrainz"
        ]
        .astype("string")
        .replace(
            "<NA>",
            pd.NA
        )

    )


    reviews[
        "artist_name_dataset"
    ] = (

        reviews[
            "artist_name_dataset"
        ]
        .astype("string")
        .replace(
            "<NA>",
            pd.NA
        )

    )


    # ========================================================
    # TEXT LENGTH FEATURES
    # ========================================================

    reviews[
        "review_char_count"
    ] = (

        reviews[
            "review_text"
        ]
        .str.len()
        .astype(int)

    )


    reviews[
        "review_word_count"
    ] = (

        reviews[
            "review_text"
        ]
        .str.split()
        .str.len()
        .astype(int)

    )


    # ========================================================
    # SOURCE
    # ========================================================

    reviews["source"] = (
        "CritiqueBrainz"
    )


    # ========================================================
    # FINAL REVIEW-LEVEL DATASET
    # ========================================================

    prepared = reviews[

        OUTPUT_COLUMNS

    ].copy()


    prepared = prepared.sort_values(

        [
            "artist_mbid",
            "review_id"
        ]

    ).reset_index(
        drop=True
    )


    # ========================================================
    # SAVE
    # ========================================================

    prepared.to_csv(

        OUTPUT_REVIEWS,

        index=False,

        encoding="utf-8"

    )


    # ========================================================
    # SUMMARY
    # ========================================================

    print(
        f"Input rows:                    "
        f"{input_rows:,}"
    )

    print(
        f"Unmatched rows removed:        "
        f"{unmatched_removed:,}"
    )

    print(
        f"Invalid artist MBIDs removed:  "
        f"{invalid_artist_rows:,}"
    )

    print(
        f"Missing review IDs removed:    "
        f"{missing_review_ids:,}"
    )

    print(
        f"Duplicate review IDs removed:  "
        f"{duplicates_removed:,}"
    )

    print(
        f"Empty review texts removed:    "
        f"{empty_text_removed:,}"
    )

    print(
        f"Invalid ratings set missing:   "
        f"{invalid_ratings:,}"
    )

    print()

    print(
        f"Prepared reviews:              "
        f"{len(prepared):,}"
    )

    print(
        f"Artists represented:           "
        f"{prepared['artist_mbid'].nunique():,}"
    )

    print()

    print(
        "Prepared review output:"
    )

    print(
        OUTPUT_REVIEWS
    )


    return prepared


# ============================================================
# CREATE ARTIST-LEVEL SUMMARY
# ============================================================


def create_music_review_summary(
    prepared
):
    """
    Create one row per artist containing descriptive
    CritiqueBrainz review statistics.

    These statistics are metadata only.

    Sentence-BERT will continue to operate on individual
    review text from music_reviews_prepared.csv.
    """

    print()
    print("=" * 60)
    print("CREATING MUSIC REVIEW SUMMARY")
    print("=" * 60)
    print()


    if prepared.empty:

        raise ValueError(
            "Prepared music review dataset is empty."
        )


    # ========================================================
    # BASE AGGREGATION
    # ========================================================

    summary = (

        prepared
        .groupby(
            "artist_mbid"
        )
        .agg(

            review_count=(
                "review_id",
                "size"
            ),

            review_rating_count=(
                "rating",
                "count"
            ),

            review_rating_mean=(
                "rating",
                "mean"
            ),

            review_rating_std=(
                "rating",
                "std"
            ),

            avg_review_char_count=(
                "review_char_count",
                "mean"
            ),

            avg_review_word_count=(
                "review_word_count",
                "mean"
            )

        )
        .reset_index()

    )


    # ========================================================
    # REVIEW SOURCE COUNTS
    # ========================================================

    source_counts = (

        prepared
        .pivot_table(

            index=
                "artist_mbid",

            columns=
                "original_entity_type",

            values=
                "review_id",

            aggfunc=
                "count",

            fill_value=
                0

        )

    )


    # --------------------------------------------------------
    # Ensure expected source columns exist even if a future
    # input dataset has none of that particular type.
    # --------------------------------------------------------

    for column in [

        "artist",

        "release",

        "release_group"

    ]:

        if column not in (
            source_counts.columns
        ):

            source_counts[
                column
            ] = 0


    source_counts = (

        source_counts[
            [
                "artist",
                "release",
                "release_group"
            ]
        ]
        .rename(

            columns={

                "artist":
                    "direct_artist_review_count",

                "release":
                    "release_review_count",

                "release_group":
                    "release_group_review_count"

            }

        )
        .reset_index()

    )


    summary = summary.merge(

        source_counts,

        on="artist_mbid",

        how="left"

    )


    # ========================================================
    # CLEAN TYPES
    # ========================================================

    integer_columns = [

        "review_count",

        "review_rating_count",

        "direct_artist_review_count",

        "release_review_count",

        "release_group_review_count",

    ]


    for column in integer_columns:

        summary[column] = (

            summary[column]
            .fillna(0)
            .astype(int)

        )


    # ========================================================
    # SORT
    # ========================================================

    summary = (

        summary
        .sort_values(
            "artist_mbid"
        )
        .reset_index(
            drop=True
        )

    )


    # ========================================================
    # SAVE
    # ========================================================

    summary.to_csv(

        OUTPUT_SUMMARY,

        index=False,

        encoding="utf-8"

    )


    # ========================================================
    # INFORMATION
    # ========================================================

    print(
        f"Artists with prepared reviews: "
        f"{len(summary):,}"
    )

    print(
        f"Total reviews represented:     "
        f"{summary['review_count'].sum():,}"
    )

    print(
        f"Artists with >= 1 review:       "
        f"{int((summary['review_count'] >= 1).sum()):,}"
    )

    print(
        f"Artists with >= 2 reviews:      "
        f"{int((summary['review_count'] >= 2).sum()):,}"
    )

    print(
        f"Artists with >= 3 reviews:      "
        f"{int((summary['review_count'] >= 3).sum()):,}"
    )

    print(
        f"Artists with >= 5 reviews:      "
        f"{int((summary['review_count'] >= 5).sum()):,}"
    )

    print(
        f"Artists with >= 10 reviews:     "
        f"{int((summary['review_count'] >= 10).sum()):,}"
    )

    print()

    print(
        "Artist-level summary output:"
    )

    print(
        OUTPUT_SUMMARY
    )


    return summary


# ============================================================
# MAIN
# ============================================================


def main():

    print()
    print("=" * 60)
    print("MUSIC REVIEW PREPARATION")
    print("=" * 60)


    # --------------------------------------------------------
    # Step 1:
    # Clean review-level data
    # --------------------------------------------------------

    prepared = (
        prepare_review_dataset()
    )


    # --------------------------------------------------------
    # Step 2:
    # Create artist-level metadata summary
    # --------------------------------------------------------

    create_music_review_summary(
        prepared
    )


    print()
    print("=" * 60)
    print("MUSIC REVIEW PREPARATION COMPLETE")
    print("=" * 60)
    print()

    print(
        "Review-level dataset:"
    )

    print(
        OUTPUT_REVIEWS
    )

    print()

    print(
        "Artist-level summary:"
    )

    print(
        OUTPUT_SUMMARY
    )

    print()


# ============================================================
# ENTRY POINT
# ============================================================


if __name__ == "__main__":

    main()