# src/domains/restaurants/evaluate_fusion_weights.py

# ============================================================
# EVALUATE RESTAURANT SEMANTIC FUSION WEIGHTS
#
# Purpose:
#
#   Determine how much influence Yelp full-review
#   Sentence-BERT embeddings should have relative to the
#   existing Restaurant TF-IDF semantic representation.
#
#
# Existing representation:
#
#       restaurant categories + tips
#                   ↓
#               tags_text
#                   ↓
#                 TF-IDF
#                   ↓
#             TruncatedSVD
#                   ↓
#            L2 normalization
#
#
# New representation:
#
#       Yelp full reviews
#             ↓
#        Sentence-BERT
#             ↓
#       mean pooling
#             ↓
#       L2 normalization
#
#
# Fusion similarity:
#
#       (1 - review_share) * TF-IDF similarity
#
#                   +
#
#       review_share * review similarity
#
#
# For each candidate review share:
#
#   1. Construct fused semantic similarities
#   2. Find nearest neighbours
#   3. Measure those neighbours in:
#
#        - original TF-IDF space
#        - review embedding space
#
#   4. Combine both coherence measures using
#      a harmonic mean
#
#
# IMPORTANT:
#
#   This is an unsupervised diagnostic criterion.
#
#   It should not be interpreted as objective ground-truth
#   accuracy.
#
# ============================================================


from pathlib import Path
import json

import numpy as np
import pandas as pd


from sklearn.feature_extraction.text import (
    TfidfVectorizer
)

from sklearn.decomposition import (
    TruncatedSVD
)

from sklearn.preprocessing import (
    normalize
)


# ============================================================
# PATHS
# ============================================================

ROOT = Path(__file__).resolve().parents[3]


# ------------------------------------------------------------
# Current Restaurant atlas
#
# text.tags contains the existing tags_text representation
# generated by the Restaurant pipeline.
#
# This means the evaluation uses the same restaurant
# population and original textual semantics as the current
# atlas.
# ------------------------------------------------------------

ATLAS_FILE = (
    ROOT
    / "frontend"
    / "public"
    / "data"
    / "restaurants"
    / "atlas.json"
)


# ------------------------------------------------------------
# Yelp Sentence-BERT restaurant embeddings
# ------------------------------------------------------------

REVIEW_EMBEDDINGS_FILE = (
    ROOT
    / "data"
    / "processed"
    / "embeddings"
    / "restaurants"
    / "restaurant_review_embeddings.npz"
)


# ------------------------------------------------------------
# Evaluation output
# ------------------------------------------------------------

OUTPUT_DIR = (
    ROOT
    / "data"
    / "processed"
    / "evaluation"
)


OUTPUT_FILE = (
    OUTPUT_DIR
    / "restaurant_fusion_weight_evaluation.csv"
)


# ============================================================
# CONFIGURATION
# ============================================================


# ------------------------------------------------------------
# Existing TF-IDF representation
# ------------------------------------------------------------

TFIDF_MAX_FEATURES = 5000

TFIDF_COMPONENTS = 256


# ------------------------------------------------------------
# Review threshold
#
# Every Restaurant atlas entity has at least 20 Yelp reviews,
# so setting this to 1 does not actually admit poorly
# represented restaurants.
#
# It simply means:
#
#     use every restaurant having a review embedding.
# ------------------------------------------------------------

MIN_REVIEWS = 1


# ------------------------------------------------------------
# Evaluation sample
#
# Same configuration used for Movies and Music.
# ------------------------------------------------------------

MAX_EVALUATION_SAMPLE = 3000


# ------------------------------------------------------------
# Number of nearest neighbours
# ------------------------------------------------------------

K_NEIGHBORS = 15


# ------------------------------------------------------------
# Reproducibility
# ------------------------------------------------------------

RANDOM_STATE = 42


# ------------------------------------------------------------
# Candidate REVIEW shares
#
# 0.00 = original TF-IDF only
# 1.00 = full Yelp reviews only
# ------------------------------------------------------------

REVIEW_SHARES = [

    0.00,

    0.20,

    0.35,

    0.50,

    0.65,

    0.80,

    1.00,

]


# ============================================================
# PRINT SECTION
# ============================================================


def section(
    title
):

    print()

    print(
        "=" * 65
    )

    print(
        title
    )

    print(
        "=" * 65
    )

    print()


# ============================================================
# LOAD CURRENT RESTAURANT ATLAS
# ============================================================


def load_restaurant_atlas():
    """
    Load the current Restaurant atlas.

    Returns a dataframe containing:

        business_id
        restaurant_name
        tags_text
    """

    section(
        "LOADING CURRENT RESTAURANT ATLAS"
    )


    if not ATLAS_FILE.exists():

        raise FileNotFoundError(

            "Current Restaurant atlas was not found:\n\n"

            f"{ATLAS_FILE}"

        )


    with open(

        ATLAS_FILE,

        "r",

        encoding="utf-8"

    ) as file:

        data = json.load(
            file
        )


    # --------------------------------------------------------
    # Support:
    #
    #   [node, node, ...]
    #
    # or:
    #
    #   {"atlas": [...]}
    # --------------------------------------------------------

    if isinstance(
        data,
        list
    ):

        nodes = data


    elif (

        isinstance(
            data,
            dict
        )

        and

        isinstance(
            data.get("atlas"),
            list
        )

    ):

        nodes = data[
            "atlas"
        ]


    else:

        raise ValueError(

            "Unexpected Restaurant atlas JSON structure."

        )


    records = []


    for node in nodes:


        # ====================================================
        # BUSINESS ID
        # ====================================================

        business_id = (

            node.get(
                "source_id"
            )

            or

            node.get(
                "id"
            )

        )


        if business_id is None:

            continue


        business_id = str(
            business_id
        ).strip()


        if not business_id:

            continue


        # ====================================================
        # NAME
        # ====================================================

        restaurant_name = node.get(
            "title"
        )


        # ====================================================
        # EXISTING SEMANTIC TEXT
        #
        # dataframe_to_items exports tags_text into
        # node.text.tags.
        #
        # For Restaurants, this represents the existing
        # categories / tips semantic information.
        # ====================================================

        text_features = node.get(
            "text",
            {}
        )


        tags = text_features.get(
            "tags",
            []
        )


        if isinstance(
            tags,
            list
        ):

            tags_text = " ".join(

                str(tag)

                for tag in tags

                if tag is not None

            )


        elif tags is None:

            tags_text = ""


        else:

            tags_text = str(
                tags
            )


        tags_text = tags_text.strip()


        # ----------------------------------------------------
        # Defensive fallback.
        #
        # Normally tags_text should already contain the
        # original Restaurant semantic text.
        #
        # If it is empty, categories provide a minimal
        # semantic representation.
        # ----------------------------------------------------

        if not tags_text:

            categories = text_features.get(
                "categories",
                []
            )


            if isinstance(
                categories,
                list
            ):

                tags_text = " ".join(

                    str(category)

                    for category
                    in categories

                    if category is not None

                )


        records.append({

            "business_id":
                business_id,

            "restaurant_name":
                restaurant_name,

            "tags_text":
                tags_text,

        })


    restaurants = pd.DataFrame(
        records
    )


    # ========================================================
    # DUPLICATE VALIDATION
    # ========================================================

    duplicate_count = int(

        restaurants[
            "business_id"
        ]
        .duplicated()
        .sum()

    )


    if duplicate_count > 0:

        raise ValueError(

            f"Current Restaurant atlas contains "
            f"{duplicate_count:,} duplicate business IDs."

        )


    restaurants = (
        restaurants
        .reset_index(
            drop=True
        )
    )


    print(
        f"Restaurant atlas items: "
        f"{len(restaurants):,}"
    )


    print(
        f"Restaurants with semantic text: "
        f"{int((restaurants['tags_text'] != '').sum()):,}"
    )


    print(
        f"Restaurants without semantic text: "
        f"{int((restaurants['tags_text'] == '').sum()):,}"
    )


    return restaurants


# ============================================================
# BUILD TF-IDF REPRESENTATION
# ============================================================


def build_tfidf_representation(
    restaurants
):
    """
    Rebuild the original Restaurant TF-IDF representation.

    TF-IDF is fit on the complete current Restaurant atlas,
    not only the evaluation sample.
    """

    section(
        "BUILDING RESTAURANT TF-IDF REPRESENTATION"
    )


    vectorizer = TfidfVectorizer(

        max_features=
            TFIDF_MAX_FEATURES,

        stop_words=
            "english"

    )


    tfidf_matrix = (
        vectorizer.fit_transform(

            restaurants[
                "tags_text"
            ]

        )
    )


    print(
        f"TF-IDF matrix shape: "
        f"{tfidf_matrix.shape}"
    )


    # ========================================================
    # SVD
    # ========================================================

    max_components = min(

        TFIDF_COMPONENTS,

        tfidf_matrix.shape[0] - 1,

        tfidf_matrix.shape[1] - 1,

    )


    if max_components < 2:

        raise ValueError(

            "Not enough TF-IDF dimensions for "
            "semantic reduction."

        )


    print(

        f"Reducing "
        f"{tfidf_matrix.shape[1]:,}D "
        f"-> "
        f"{max_components:,}D"

    )


    svd = TruncatedSVD(

        n_components=
            max_components,

        random_state=
            RANDOM_STATE

    )


    tfidf_reduced = (
        svd.fit_transform(
            tfidf_matrix
        )
    )


    explained_variance = float(

        svd
        .explained_variance_ratio_
        .sum()

    )


    print(
        f"SVD explained variance: "
        f"{explained_variance:.4f}"
    )


    # ========================================================
    # NORMALIZE
    # ========================================================

    tfidf_reduced = normalize(

        tfidf_reduced,

        norm="l2",

        axis=1

    ).astype(
        np.float32
    )


    return (
        tfidf_reduced,
        explained_variance
    )


# ============================================================
# ALIGN REVIEW EMBEDDINGS
# ============================================================


def align_review_embeddings(
    restaurants
):
    """
    Align Yelp review embeddings with the row order of the
    current Restaurant atlas.
    """

    section(
        "ALIGNING YELP REVIEW EMBEDDINGS"
    )


    if not REVIEW_EMBEDDINGS_FILE.exists():

        raise FileNotFoundError(

            "Restaurant review embeddings were not found:\n\n"

            f"{REVIEW_EMBEDDINGS_FILE}"

        )


    data = np.load(

        REVIEW_EMBEDDINGS_FILE,

        allow_pickle=True

    )


    required_keys = {

        "entity_ids",

        "embeddings",

        "review_counts",

    }


    missing_keys = (

        required_keys

        -

        set(
            data.files
        )

    )


    if missing_keys:

        raise ValueError(

            "Restaurant review embedding file is missing "
            f"required arrays: "
            f"{sorted(missing_keys)}"

        )


    review_ids = [

        str(value).strip()

        for value
        in data[
            "entity_ids"
        ]

    ]


    review_embeddings = np.asarray(

        data[
            "embeddings"
        ],

        dtype=np.float32

    )


    review_counts = np.asarray(

        data[
            "review_counts"
        ],

        dtype=np.int32

    )


    if (

        len(review_ids)
        !=
        review_embeddings.shape[0]

        or

        len(review_ids)
        !=
        len(review_counts)

    ):

        raise ValueError(

            "Restaurant review embedding arrays "
            "are not aligned."

        )


    # --------------------------------------------------------
    # Normalize defensively.
    # --------------------------------------------------------

    review_embeddings = normalize(

        review_embeddings,

        norm="l2",

        axis=1

    ).astype(
        np.float32
    )


    review_lookup = {

        business_id:
            index

        for index, business_id
        in enumerate(
            review_ids
        )

    }


    embedding_dimension = (
        review_embeddings.shape[1]
    )


    aligned_embeddings = np.zeros(

        (
            len(
                restaurants
            ),

            embedding_dimension
        ),

        dtype=np.float32

    )


    aligned_counts = np.zeros(

        len(
            restaurants
        ),

        dtype=np.int32

    )


    aligned_entities = 0


    for index, business_id in enumerate(

        restaurants[
            "business_id"
        ]

    ):

        review_index = (
            review_lookup.get(

                str(
                    business_id
                ).strip()

            )
        )


        if review_index is None:

            continue


        aligned_embeddings[
            index
        ] = review_embeddings[
            review_index
        ]


        aligned_counts[
            index
        ] = review_counts[
            review_index
        ]


        aligned_entities += 1


    print(
        f"Review embeddings available: "
        f"{len(review_ids):,}"
    )


    print(
        f"Review embeddings aligned:   "
        f"{aligned_entities:,} / "
        f"{len(restaurants):,} restaurants"
    )


    print(
        f"Review embedding dimensions: "
        f"{embedding_dimension:,}"
    )


    return (
        aligned_embeddings,
        aligned_counts
    )


# ============================================================
# SELECT EVALUATION SAMPLE
# ============================================================


def select_evaluation_sample(

    restaurants,

    tfidf_embeddings,

    review_embeddings,

    review_counts

):
    """
    Select restaurants having valid information in both
    semantic spaces.
    """

    section(
        "SELECTING EVALUATION RESTAURANTS"
    )


    tfidf_norms = np.linalg.norm(

        tfidf_embeddings,

        axis=1

    )


    review_norms = np.linalg.norm(

        review_embeddings,

        axis=1

    )


    eligible_mask = (

        (
            review_counts
            >=
            MIN_REVIEWS
        )

        &

        (
            tfidf_norms
            > 0
        )

        &

        (
            review_norms
            > 0
        )

    )


    eligible_indices = np.flatnonzero(

        eligible_mask

    )


    print(
        f"Minimum reviews required: "
        f"{MIN_REVIEWS}"
    )


    print(
        f"Eligible restaurants: "
        f"{len(eligible_indices):,}"
    )


    if len(
        eligible_indices
    ) < (
        K_NEIGHBORS + 1
    ):

        raise ValueError(

            "Too few eligible restaurants for "
            "nearest-neighbour evaluation."

        )


    # ========================================================
    # DETERMINISTIC SAMPLE
    # ========================================================

    if (

        len(
            eligible_indices
        )

        >

        MAX_EVALUATION_SAMPLE

    ):

        rng = np.random.default_rng(

            RANDOM_STATE

        )


        sample_indices = rng.choice(

            eligible_indices,

            size=
                MAX_EVALUATION_SAMPLE,

            replace=False

        )


        sample_indices = np.sort(

            sample_indices

        )


    else:

        sample_indices = (
            eligible_indices
        )


    print(
        f"Evaluation sample: "
        f"{len(sample_indices):,}"
    )


    # --------------------------------------------------------
    # Note:
    #
    # review_counts here represents reviews ACTUALLY used
    # for embedding and is therefore capped at 50.
    # --------------------------------------------------------

    sampled_review_counts = (
        review_counts[
            sample_indices
        ]
    )


    print()

    print(
        "Reviews used per sampled restaurant:"
    )


    print(

        pd.Series(
            sampled_review_counts
        )
        .describe(

            percentiles=[

                0.25,

                0.50,

                0.75,

                0.90,

                0.95,

                0.99,

            ]

        )
        .to_string()

    )


    return sample_indices


# ============================================================
# COSINE SIMILARITY MATRIX
# ============================================================


def cosine_similarity_matrix(
    embeddings
):
    """
    Embeddings are L2-normalized.

    Therefore:

        cosine similarity
            =
        matrix dot product
    """

    return (

        embeddings

        @

        embeddings.T

    ).astype(
        np.float32
    )


# ============================================================
# NEAREST NEIGHBOURS
# ============================================================


def nearest_neighbors(

    similarity_matrix,

    k

):
    """
    Return K nearest neighbours for each restaurant.
    """

    similarities = (
        similarity_matrix.copy()
    )


    # --------------------------------------------------------
    # Remove self similarity
    # --------------------------------------------------------

    np.fill_diagonal(

        similarities,

        -np.inf

    )


    # --------------------------------------------------------
    # Efficient top-K selection
    # --------------------------------------------------------

    neighbor_indices = np.argpartition(

        -similarities,

        kth=
            k - 1,

        axis=1

    )[
        :,
        :k
    ]


    # --------------------------------------------------------
    # Sort selected neighbours by similarity
    # --------------------------------------------------------

    row_indices = np.arange(

        similarities.shape[0]

    )[
        :,
        None
    ]


    selected_similarities = (

        similarities[

            row_indices,

            neighbor_indices

        ]

    )


    ordering = np.argsort(

        -selected_similarities,

        axis=1

    )


    neighbor_indices = np.take_along_axis(

        neighbor_indices,

        ordering,

        axis=1

    )


    return neighbor_indices


# ============================================================
# MEAN NEIGHBOUR COHERENCE
# ============================================================


def mean_neighbor_coherence(

    reference_similarity,

    neighbor_indices

):
    """
    Measure how similar each restaurant is to its selected
    fused-space neighbours according to a reference space.
    """

    row_indices = np.arange(

        reference_similarity.shape[0]

    )[
        :,
        None
    ]


    values = reference_similarity[

        row_indices,

        neighbor_indices

    ]


    return float(
        values.mean()
    )


# ============================================================
# BALANCED SCORE
# ============================================================


def balanced_score(

    tfidf_coherence,

    review_coherence

):
    """
    Convert cosine similarities from [-1, 1] to [0, 1].

    Then combine both semantic coherence measures using
    their harmonic mean.
    """


    tfidf_scaled = (

        tfidf_coherence
        +
        1.0

    ) / 2.0


    review_scaled = (

        review_coherence
        +
        1.0

    ) / 2.0


    denominator = (

        tfidf_scaled
        +
        review_scaled

    )


    if denominator <= 0:

        return 0.0


    return float(

        2.0

        *

        tfidf_scaled

        *

        review_scaled

        /

        denominator

    )


# ============================================================
# EVALUATE REVIEW SHARES
# ============================================================


def evaluate_weights(

    tfidf_similarity,

    review_similarity

):

    section(
        "EVALUATING FUSION WEIGHTS"
    )


    results = []


    print(

        f"{'Review share':>12} | "
        f"{'TF-IDF coherence':>16} | "
        f"{'Review coherence':>16} | "
        f"{'Balanced':>10}"

    )


    print(
        "-" * 65
    )


    for review_share in (
        REVIEW_SHARES
    ):


        tfidf_share = (

            1.0

            -

            review_share

        )


        # ----------------------------------------------------
        # Because both semantic blocks are normalized and
        # semantic_fusion uses:
        #
        #     sqrt(1-r) * TF-IDF
        #     sqrt(r)   * Reviews
        #
        # fused cosine similarity becomes:
        #
        #     (1-r) * TF-IDF similarity
        #          +
        #      r    * Review similarity
        # ----------------------------------------------------

        fused_similarity = (

            tfidf_share
            *
            tfidf_similarity

            +

            review_share
            *
            review_similarity

        )


        neighbors = nearest_neighbors(

            fused_similarity,

            K_NEIGHBORS

        )


        tfidf_coherence = (
            mean_neighbor_coherence(

                tfidf_similarity,

                neighbors

            )
        )


        review_coherence = (
            mean_neighbor_coherence(

                review_similarity,

                neighbors

            )
        )


        score = balanced_score(

            tfidf_coherence,

            review_coherence

        )


        results.append({

            "review_share":
                review_share,

            "tfidf_share":
                tfidf_share,

            "tfidf_coherence":
                tfidf_coherence,

            "review_coherence":
                review_coherence,

            "balanced_score":
                score,

        })


        print(

            f"{review_share:12.2f} | "
            f"{tfidf_coherence:16.4f} | "
            f"{review_coherence:16.4f} | "
            f"{score:10.4f}"

        )


    return pd.DataFrame(
        results
    )


# ============================================================
# MAIN
# ============================================================


def main():

    section(
        "RESTAURANT FUSION WEIGHT EVALUATION"
    )


    print(
        "Configuration:"
    )


    print(
        f"  TF-IDF max features: "
        f"{TFIDF_MAX_FEATURES:,}"
    )


    print(
        f"  TF-IDF SVD dimensions: "
        f"{TFIDF_COMPONENTS:,}"
    )


    print(
        f"  Minimum reviews: "
        f"{MIN_REVIEWS}"
    )


    print(
        f"  Maximum sample size: "
        f"{MAX_EVALUATION_SAMPLE:,}"
    )


    print(
        f"  Neighbours: "
        f"{K_NEIGHBORS}"
    )


    print(
        f"  Random state: "
        f"{RANDOM_STATE}"
    )


    # ========================================================
    # 1. CURRENT RESTAURANT ATLAS
    # ========================================================

    restaurants = (
        load_restaurant_atlas()
    )


    # ========================================================
    # 2. ORIGINAL TF-IDF SEMANTICS
    # ========================================================

    (
        tfidf_embeddings,
        explained_variance

    ) = build_tfidf_representation(

        restaurants

    )


    # ========================================================
    # 3. REVIEW EMBEDDINGS
    # ========================================================

    (
        review_embeddings,
        review_counts

    ) = align_review_embeddings(

        restaurants

    )


    # ========================================================
    # 4. EVALUATION SAMPLE
    # ========================================================

    sample_indices = (
        select_evaluation_sample(

            restaurants,

            tfidf_embeddings,

            review_embeddings,

            review_counts

        )
    )


    # ========================================================
    # 5. SAMPLE REPRESENTATIONS
    # ========================================================

    tfidf_sample = (

        tfidf_embeddings[
            sample_indices
        ]

    )


    review_sample = (

        review_embeddings[
            sample_indices
        ]

    )


    # --------------------------------------------------------
    # Normalize defensively
    # --------------------------------------------------------

    tfidf_sample = normalize(

        tfidf_sample,

        norm="l2",

        axis=1

    ).astype(
        np.float32
    )


    review_sample = normalize(

        review_sample,

        norm="l2",

        axis=1

    ).astype(
        np.float32
    )


    # ========================================================
    # 6. SIMILARITY MATRICES
    # ========================================================

    section(
        "COMPUTING SIMILARITY MATRICES"
    )


    print(

        f"Matrix size: "
        f"{len(sample_indices):,} × "
        f"{len(sample_indices):,}"

    )


    tfidf_similarity = (
        cosine_similarity_matrix(
            tfidf_sample
        )
    )


    review_similarity = (
        cosine_similarity_matrix(
            review_sample
        )
    )


    print(
        "Similarity matrices complete."
    )


    # ========================================================
    # 7. FUSION EVALUATION
    # ========================================================

    results = evaluate_weights(

        tfidf_similarity,

        review_similarity

    )


    # ========================================================
    # 8. METADATA
    # ========================================================

    results[
        "evaluation_sample_size"
    ] = len(
        sample_indices
    )


    results[
        "min_reviews"
    ] = MIN_REVIEWS


    results[
        "k_neighbors"
    ] = K_NEIGHBORS


    results[
        "tfidf_components"
    ] = tfidf_sample.shape[1]


    results[
        "review_dimensions"
    ] = review_sample.shape[1]


    results[
        "svd_explained_variance"
    ] = explained_variance


    # ========================================================
    # 9. SAVE
    # ========================================================

    OUTPUT_DIR.mkdir(

        parents=True,

        exist_ok=True

    )


    results.to_csv(

        OUTPUT_FILE,

        index=False

    )


    # ========================================================
    # 10. BEST RESULT
    # ========================================================

    best_index = (

        results[
            "balanced_score"
        ]
        .idxmax()

    )


    best = results.loc[
        best_index
    ]


    section(
        "EVALUATION COMPLETE"
    )


    print(
        "Best diagnostic result:"
    )


    print()


    print(
        f"Review share:       "
        f"{best['review_share']:.2f}"
    )


    print(
        f"TF-IDF share:       "
        f"{best['tfidf_share']:.2f}"
    )


    print(
        f"TF-IDF coherence:   "
        f"{best['tfidf_coherence']:.4f}"
    )


    print(
        f"Review coherence:   "
        f"{best['review_coherence']:.4f}"
    )


    print(
        f"Balanced score:     "
        f"{best['balanced_score']:.4f}"
    )


    print()


    print(
        "IMPORTANT:"
    )


    print(

        "The maximum balanced score should be interpreted "
        "as a diagnostic recommendation, not as objective "
        "ground truth."

    )


    print()


    print(
        "Output:"
    )


    print(
        OUTPUT_FILE
    )


    print()


# ============================================================
# ENTRY POINT
# ============================================================


if __name__ == "__main__":

    main()